import { TTokenInfo } from "./types/wallet";

export type TokensConfig = TTokenInfo[];

const tokensConfig = [
  {
    contractName: "Wood",
    name: "Wood",
    emoji: "🌲",
    initAssetAmount: "500.5",
    initCreditAmount: "1000",
  },
  {
    contractName: "Stone",
    name: "Stone",
    emoji: "🪨",
    initAssetAmount: "667.3333333333334",
    initCreditAmount: "1000",
  },
  {
    contractName: "Copper",
    name: "Copper",
    emoji: "🥉",
    initAssetAmount: "200.2",
    initCreditAmount: "1000",
  },
  {
    contractName: "Corn",
    name: "Corn",
    emoji: "🌽",
    initAssetAmount: "1251.25",
    initCreditAmount: "1000",
  },
  {
    contractName: "Wheat",
    name: "Wheat",
    emoji: "🌾",
    initAssetAmount: "1001",
    initCreditAmount: "1000",
  },
  {
    contractName: "Bread",
    name: "Bread",
    emoji: "🍞",
    initAssetAmount: "400.4",
    initCreditAmount: "1000",
  },
  {
    contractName: "Gold",
    name: "Gold",
    emoji: "💰",
    initAssetAmount: "20.02",
    initCreditAmount: "1000",
  },
  {
    contractName: "Iron",
    name: "Iron",
    emoji: "⛓",
    initAssetAmount: "100.1",
    initCreditAmount: "1000",
  },
  {
    contractName: "Horse",
    name: "Horse",
    emoji: "🐎",
    initAssetAmount: "25.025",
    initCreditAmount: "1000",
  },
  {
    contractName: "Cloth",
    name: "Cloth",
    emoji: "👕",
    initAssetAmount: "500.5",
    initCreditAmount: "1000",
  },
  {
    contractName: "Silk",
    name: "Silk",
    emoji: "👘",
    initAssetAmount: "66.73333333333333",
    initCreditAmount: "1000",
  },
  {
    contractName: "Wine",
    name: "Wine",
    emoji: "🍷",
    initAssetAmount: "40.04",
    initCreditAmount: "1000",
  },
  {
    contractName: "Oil",
    name: "Oil",
    emoji: "🛢",
    initAssetAmount: "33.36666666666667",
    initCreditAmount: "1000",
  },
  {
    contractName: "Spice",
    name: "Spice",
    emoji: "🧂",
    initAssetAmount: "50.05",
    initCreditAmount: "1000",
  },
  {
    contractName: "Sugar",
    name: "Sugar",
    emoji: "🍚",
    initAssetAmount: "250.25",
    initCreditAmount: "1000",
  },
  {
    contractName: "Leather",
    name: "Leather",
    emoji: "🛡",
    initAssetAmount: "83.41666666666667",
    initCreditAmount: "1000",
  },
  {
    contractName: "Rice",
    name: "Rice",
    emoji: "🍚",
    initAssetAmount: "1668.3333333333335",
    initCreditAmount: "1000",
  },
  {
    contractName: "Salt",
    name: "Salt",
    emoji: "🧂",
    initAssetAmount: "2502.5",
    initCreditAmount: "1000",
  },
  {
    contractName: "Cheese",
    name: "Cheese",
    emoji: "🧀",
    initAssetAmount: "333.6666666666667",
    initCreditAmount: "1000",
  },
  {
    contractName: "Fish",
    name: "Fish",
    emoji: "🐟",
    initAssetAmount: "286",
    initCreditAmount: "1000",
  },
  {
    contractName: "Meat",
    name: "Meat",
    emoji: "🍖",
    initAssetAmount: "125.125",
    initCreditAmount: "1000",
  },
  {
    contractName: "Egg",
    name: "Egg",
    emoji: "🥚",
    initAssetAmount: "3336.666666666667",
    initCreditAmount: "1000",
  },
  {
    contractName: "Milk",
    name: "Milk",
    emoji: "🥛",
    initAssetAmount: "500.5",
    initCreditAmount: "1000",
  },
  {
    contractName: "Fruit",
    name: "Fruit",
    emoji: "🍎",
    initAssetAmount: "834.1666666666667",
    initCreditAmount: "1000",
  },
  {
    contractName: "Vegetable",
    name: "Vegetable",
    emoji: "🍅",
    initAssetAmount: "2002",
    initCreditAmount: "1000",
  },
  {
    contractName: "Silver",
    name: "Silver",
    emoji: "🪙",
    initAssetAmount: "143",
    initCreditAmount: "1000",
  },
  {
    contractName: "Bronze",
    name: "Bronze",
    emoji: "🔗",
    initAssetAmount: "250.25",
    initCreditAmount: "1000",
  },
  {
    contractName: "Coal",
    name: "Coal",
    emoji: "🔥",
    initAssetAmount: "166.83333333333334",
    initCreditAmount: "1000",
  },
  {
    contractName: "Potato",
    name: "Potato",
    emoji: "🥔",
    initAssetAmount: "1430",
    initCreditAmount: "1000",
  },
  {
    contractName: "Clay",
    name: "Clay",
    emoji: "🏺",
    initAssetAmount: "333.6666666666667",
    initCreditAmount: "1000",
  },
  {
    contractName: "Pearl",
    name: "Pearl",
    emoji: "🦪",
    initAssetAmount: "22.244444444444444",
    initCreditAmount: "1000",
  },
  {
    contractName: "Honey",
    name: "Honey",
    emoji: "🍯",
    initAssetAmount: "200.2",
    initCreditAmount: "1000",
  },
] satisfies TokensConfig;

export default tokensConfig;
