name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BURNER_ADDRESS: "0x92C8Fd39A4582E6Fe8bb5Be6e7Fdf6533566EA69"

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Copy tokens config
        run: cp packages/nextjs/tokens.config.ts.example packages/nextjs/tokens.config.ts

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run hardhat node, deploy contracts (& generate contracts typescript output)
        run: yarn chain & yarn deploy

      - name: Run nextjs lint
        run: yarn next:lint

      - name: Check typings on nextjs
        run: yarn next:check-types

      - name: Run hardhat lint
        run: yarn hardhat:lint --max-warnings=0
